services:
  - type: web
    name: isidore-clinic
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: "Isidore Animal Clinic"
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://isidore-clinic.onrender.com"
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
